//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otogaleri_KayaOtogaleri__DbFirst_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusteriBilgileri()
        {
            this.SubeBilgileris = new HashSet<SubeBilgileri>();
        }
    
        public int MusteriNo { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string MusteriTelefon { get; set; }
        public Nullable<int> MusteriYas { get; set; }
        public Nullable<decimal> MusteriBakiye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubeBilgileri> SubeBilgileris { get; set; }
    }
}
